env:
  es6: true
  node: true
  browser: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
  sourceType: module
plugins:
  - html
  - svelte3
settings:
  # Ignore style tags because we are using scss in many
  svelte3/ignore-styles: true
  html:
    indent: 0
    report-bad-indent: error
    html-extensions:
      - .html
      #- .svelte
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
      MemberExpression: 1
      ArrayExpression: 1
      ObjectExpression: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-var:
    - error
  prefer-const:
    - error
  no-unused-vars:
    - error
    - args: none
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: false
  eol-last:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  keyword-spacing:
    - error
    - before: true
      after: true
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: strict
  comma-spacing:
    - error
  arrow-spacing:
    - error
  array-bracket-spacing:
    - error
    - never
    - singleValue: false
      objectsInArrays: true
      arraysInArrays: true
  curly:
    - error
  space-infix-ops:
    - error
    - int32Hint: false
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  space-before-blocks:
    - error
  object-curly-spacing:
    - error
    - never
  space-in-parens:
    - error
    - never
  prefer-arrow-callback:
    - error
  no-return-await:
    - error
  no-console:
    - error
  no-nested-ternary:
    - error
  no-unneeded-ternary:
    - error
  no-unexpected-multiline:
    - error
  lines-around-directive:
    - error
    - always
  no-multiple-empty-lines:
    - error
    - max: 1
  operator-linebreak:
    - error
    - after
